apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: "techchallenge-rds.c3qig4kemrm8.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "techchallenge"
  init_database.sql: |
    CREATE ROLE techchallenge_usr NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD 'P0o9i8u7';
    ALTER DATABASE techchallenge OWNER TO techchallenge_usr;
