apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: "<RDS-ENDPOINT"
  DB_PORT: "5432"
  DB_NAME: "techchallenge"
  init_database.sql: |
    CREATE ROLE techchallenge_usr NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD 'P0o9i8u7';
    ALTER DATABASE techchallenge OWNER TO techchallenge_usr;