apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2  
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sickbanger/techchallenge-backend:latest
        ports:
        - containerPort: 8080
        command: ["mvn"]
        args: ["clean", "install", "-Pprod"]
        env:
        - name: DB_HOST
          value: "techchallenge-psql"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "techchallenge"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.2
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "techchallenge"
        volumeMounts:
        - name: dbdata
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 512Mi
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: postgres-pvc
